### ISSUE TITLE
Disappointing

### ISSUE THREAD

**Issue by SRGOM** [pietroalbini/areweawaityet#1]
I was so eagerly awaiting the await syntax and when I quickly saw in larger letters `3 minutes` I thought await syntax will arrive in 3 minutes but then I read the whole thing and was so disappointed. I'm going to cry myself to sleep tonight. I just want one thing in life- the await syntax. And I cannot even have it.

**Comment by emilyalbini** [comment]
Don't worry, you just need to `a bit more.await`
